on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.9']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch main branch
        run: git fetch origin main
      - name: Check if the tag is on the main branch
        run: |
          TAG_COMMIT=$(git rev-parse HEAD)

          # Check if the tag commit is in the main branch history
          if git merge-base --is-ancestor $TAG_COMMIT origin/main; then
            echo "Tag has landed on main. Releasing!"
          else
            echo "Tag is not on main yet. Exiting."
            exit 1
          fi

      - uses: compas-dev/compas-actions.build@v3
        with:
          python: ${{ matrix.python }}
          invoke_lint: true
          check_import: true

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: compas-dev/compas-actions.publish@v2
        with:
          pypi_token: ${{ secrets.PYPI_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_ghpython_components: true
          gh_source: src/aixd_ara/components
          gh_target: src/aixd_ara/components/ghuser
          gh_prefix: ""
          gh_interpreter: "ironpython"
          release_name_prefix: ARA
