on:
  push:
    branches:
      - main

name: Create Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.9']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch all tags
        run: git fetch --tags
      - name: Check for tags
        id: check_version_tag
        run: |
          TAGS=$(git tag --points-at HEAD)
          if [[ "$TAGS" == *v* ]]; then
            echo "Version tag found! Building new release: $TAGS"
            echo "::set-output name=version_tag_exists::true"
          else
            echo "No version tag found. Skipping workflow."
            echo "::set-output name=version_tag_exists::false"
          fi

      - uses: compas-dev/compas-actions.build@v3
        if: steps.check_version_tag.outputs.version_tag_exists == 'true'
        with:
          python: ${{ matrix.python }}
          invoke_lint: true
          check_import: true

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: compas-dev/compas-actions.publish@v2
        with:
          pypi_token: ${{ secrets.PYPI_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_ghpython_components: true
          gh_source: src/aixd_ara/components
          gh_target: src/aixd_ara/components/ghuser
          gh_prefix: ""
          gh_interpreter: "ironpython"
          release_name_prefix: ARA
